apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sandboxed-containers-operator-5xzg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sandboxed-containers-operator-5xzg
    app.kubernetes.io/part-of: ose-osc
  name: sandboxed-containers-operzquo
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sandboxed-containers-operator-5xzg
    weight: 100
status: {}
