apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sandboxed-containers-operator-5xzg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sandboxed-containers-operator-5xzg
    app.kubernetes.io/part-of: ose-osc
  name: sandboxed-containers-operator-5xzg
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: sandboxed-containers-operator-5xzg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sandboxed-containers-operator-5xzg
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-dbox-containers-tenant/ose-osc/sandboxed-containers-operator-5xzg@sha256:3228a66f04282335136310ca0f66dd501f4cb86cec02be659848116fb1764662
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
